[2025-02-12T06:52:27.922+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T06:52:27.971+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:45:00+00:00 [queued]>
[2025-02-12T06:52:28.008+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:45:00+00:00 [queued]>
[2025-02-12T06:52:28.012+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T06:52:28.075+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_dim_location> on 2025-02-12 06:45:00+00:00
[2025-02-12T06:52:28.129+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T06:52:28.160+0000] {standard_task_runner.py:72} INFO - Started process 321 to run task
[2025-02-12T06:52:28.153+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19', 'create_dim_location', 'scheduled__2025-02-12T06:45:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/covid_19.py', '--cfg-path', '/tmp/tmpyk953qh7']
[2025-02-12T06:52:28.182+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask create_dim_location
[2025-02-12T06:52:28.546+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:45:00+00:00 [running]> on host e0d8147cd68a
[2025-02-12T06:52:41.968+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19' AIRFLOW_CTX_TASK_ID='create_dim_location' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T06:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T06:45:00+00:00'
[2025-02-12T06:52:41.971+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T06:52:42.212+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dim_location (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT,
            combined_key VARCHAR(500)
        );
        
[2025-02-12T06:52:42.266+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:52:42.342+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:52:42.428+0000] {sql.py:553} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dim_location (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT,
            combined_key VARCHAR(500)
        );
        , parameters: None
[2025-02-12T06:52:44.530+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T06:52:44.539+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19, task_id=create_dim_location, run_id=scheduled__2025-02-12T06:45:00+00:00, execution_date=20250212T064500, start_date=20250212T065227, end_date=20250212T065244
[2025-02-12T06:52:44.646+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T06:52:44.668+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
