[2025-02-12T06:55:04.060+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T06:55:04.107+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:50:00+00:00 [queued]>
[2025-02-12T06:55:04.132+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:50:00+00:00 [queued]>
[2025-02-12T06:55:04.133+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T06:55:04.167+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_dim_location> on 2025-02-12 06:50:00+00:00
[2025-02-12T06:55:04.188+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T06:55:04.193+0000] {standard_task_runner.py:72} INFO - Started process 381 to run task
[2025-02-12T06:55:04.193+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19', 'create_dim_location', 'scheduled__2025-02-12T06:50:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/covid_19.py', '--cfg-path', '/tmp/tmpmuwrzelp']
[2025-02-12T06:55:04.209+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask create_dim_location
[2025-02-12T06:55:04.340+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19.create_dim_location scheduled__2025-02-12T06:50:00+00:00 [running]> on host e0d8147cd68a
[2025-02-12T06:55:06.817+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19' AIRFLOW_CTX_TASK_ID='create_dim_location' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T06:50:00+00:00'
[2025-02-12T06:55:06.821+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T06:55:06.860+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dim_location (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT,
            combined_key VARCHAR(500)
        );
        
[2025-02-12T06:55:06.879+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:55:06.903+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T06:55:06.911+0000] {sql.py:553} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dim_location (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            latitude FLOAT,
            longitude FLOAT,
            combined_key VARCHAR(500)
        );
        , parameters: None
[2025-02-12T06:55:06.932+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T06:55:06.933+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19, task_id=create_dim_location, run_id=scheduled__2025-02-12T06:50:00+00:00, execution_date=20250212T065000, start_date=20250212T065504, end_date=20250212T065506
[2025-02-12T06:55:06.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T06:55:07.036+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T06:55:07.045+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
