[2025-02-12T17:47:18.019+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T17:47:18.242+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.create_tables scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T17:47:18.322+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.create_tables scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T17:47:18.324+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T17:47:18.410+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_tables> on 2025-02-11 00:00:00+00:00
[2025-02-12T17:47:18.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1353) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T17:47:18.604+0000] {standard_task_runner.py:72} INFO - Started process 1362 to run task
[2025-02-12T17:47:18.627+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'create_tables', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmp_idwnd56']
[2025-02-12T17:47:18.654+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask create_tables
[2025-02-12T17:47:19.053+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.create_tables scheduled__2025-02-11T00:00:00+00:00 [running]> on host f99369d27a52
[2025-02-12T17:47:34.607+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T17:47:34.612+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T17:47:34.725+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS dim_date_details (
            date_id SERIAL PRIMARY KEY,
            date DATE UNIQUE NOT NULL,
            year INTEGER,
            month INTEGER,
            day INTEGER,
            weekday VARCHAR(9),
            is_weekend BOOLEAN
        );

        CREATE TABLE IF NOT EXISTS dim_location_details (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            lat FLOAT,
            long_ FLOAT,
            combined_key VARCHAR(500) UNIQUE
        );

        CREATE TABLE IF NOT EXISTS fact_cases (
            case_id SERIAL PRIMARY KEY,
            date_id INTEGER REFERENCES dim_date_details(date_id),
            location_id INTEGER REFERENCES dim_location_details(location_id),
            confirmed INTEGER,
            deaths INTEGER,
            recovered INTEGER,
            active INTEGER,
            incident_rate FLOAT,
            case_fatality_ratio FLOAT
        );
        
[2025-02-12T17:47:34.793+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T17:47:34.831+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-02-12T17:47:34.842+0000] {sql.py:553} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS dim_date_details (
            date_id SERIAL PRIMARY KEY,
            date DATE UNIQUE NOT NULL,
            year INTEGER,
            month INTEGER,
            day INTEGER,
            weekday VARCHAR(9),
            is_weekend BOOLEAN
        );

        CREATE TABLE IF NOT EXISTS dim_location_details (
            location_id SERIAL PRIMARY KEY,
            fips VARCHAR(10),
            admin2 VARCHAR(255),
            province_state VARCHAR(255),
            country_region VARCHAR(255),
            lat FLOAT,
            long_ FLOAT,
            combined_key VARCHAR(500) UNIQUE
        );

        CREATE TABLE IF NOT EXISTS fact_cases (
            case_id SERIAL PRIMARY KEY,
            date_id INTEGER REFERENCES dim_date_details(date_id),
            location_id INTEGER REFERENCES dim_location_details(location_id),
            confirmed INTEGER,
            deaths INTEGER,
            recovered INTEGER,
            active INTEGER,
            incident_rate FLOAT,
            case_fatality_ratio FLOAT
        );
        , parameters: None
[2025-02-12T17:47:34.881+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T17:47:34.883+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=create_tables, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T174718, end_date=20250212T174734
[2025-02-12T17:47:35.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T17:47:35.358+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
